---------------------------------------------CUMMULATIVE ANALYSIS-----------------------------------------------------
 
 ----------AGG THE DATA PROGRESSIVELY OVERTIME IT HELPS US TO UNDERSTABD OUR BUSINESS GROWTH OR DECLINE--------------------

 ------SYNTAX = CUM MESURE BY DATE DIMESION--
 ------EXAMPLE: RUNNING TOTAL BY YEAR, MOVING AVG BY MONTH 

 ---CALCULATE THE TOTAL SALES PER YEAR AND ALSO FIND RUNNING TOTAL
---CALCULATE THE AVG SALES PER YEAR AND ALSO FIND MOVING AVG
SELECT
ORDER_BY_YEAR,
TOTAL_SALES,
SUM(TOTAL_SALES)OVER(ORDER BY ORDER_BY_YEAR)  AS RUNNING_TOTAL,
AVG_PRICE,
AVG(AVG_PRICE) OVER(ORDER BY ORDER_BY_YEAR) AS MOVING_AVG
FROM(
SELECT
DATETRUNC(YEAR,Order_Date)AS ORDER_BY_YEAR,
SUM(Sales_amount) AS TOTAL_SALES,
AVG(PRICE) AS AVG_PRICE
FROM gold.fact_sales
WHERE Order_Date IS NOT NULL
GROUP BY DATETRUNC(YEAR,Order_Date)
)t
