---------------------------DATA SEGMENTATION---------------------

--SEGMENT PRODUCTS INTO COST RANGES  AND COUNT HO MANY PRODUCTS FALL INTO EACH CATEGORY USING 
--CTE METHOD
WITH PRODUCT_SEGMENTS AS(
SELECT
Product_Key,
Product_Name,
Cost,
CASE WHEN Cost <100 THEN 'BELOW 100'
     WHEN Cost BETWEEN 100 AND 500 THEN '100-500'
	 WHEN Cost BETWEEN 500 AND 1000 THEN '500-1000'
	 ELSE 'ABOVE 1000'
END Cost_Range
FROM gold.dim_Products)

SELECT
Cost_Range,
COUNT(Product_Key) as Total_Products
FROM PRODUCT_SEGMENTS
GROUP BY Cost_Range
ORDER BY Total_Products DESC




