-------------------------------------------------DATABASE EXPLORATION-----------------------------------------------------------------

--IT IS IMPORTANT TO UNDERSTAND THE STRUCTURE OF OUR DATABASE (SALESDB) HOW MANY TABLES,  COLOUMNS  ARE THERE IN DATABASE TO ANALYZE ABOUT DATA--

-----EXPLORE ALL OBJECTS IN THE DATABASE----------

SELECT* FROM INFORMATION_SCHEMA.TABLES

-----EXPLORE ALL COLOUMNS IN THE DATABSE

SELECT*FROM INFORMATION_SCHEMA.COLUMNS
