----------------------------------DATE EXPLORATION----------------------------------------------------------------

----IDENTIFY THE EARLIEST AND OLDEST DATES(BOUNDARIES) UNDERSATND THE SCOPE OF DATA AND SPAN  HERE WE CAN FIND AGES, DATE OF BIRTHS------------

--SYNTAX= MAX/MIN[DATE DIM]
--EXAMPLE: MAX/MIN [ORDER_DATE],MAX/MIN[BIRTH_DATE] ,MAX/MIN[CRATE_DATE]

-------------FIND THE YOUNGEST AND OLDEST EMPLOYEES AND FIND THEIR AGES-----------

SELECT
MIN(BirthDate) AS OLDEST_EMPLOYEE,
DATEDIFF(YEAR,MIN(BirthDate),GETDATE()) AS  OLDEST_AGE ,
MAX(BirthDate) AS YOUNGEST_EMPLOYEE,
DATEDIFF(YEAR,MAX(BirthDate),GETDATE()) AS  YOUNGEST_AGE 
FROM Sales.Employees
