----------------------------------------DIMENSION EXPLORATION-----------------------------------------------------------

--INDENTIFY THE  UNQUE VALUES IN EACH DIMESION  RECOGNIZING HOW DATA GROUPED OR SEGMENTED----

---SYNTAX = DISTINCT[DIMENSION]
--EXAMPLE: DISTINCT[COUNTRY],DISTINCT[CATEGORY],DISTINCT[PRODUCT]--

---EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM

SELECT DISTINCT COUNTRY FROM Sales.Customers

--- EXPLORE ALL PRODUCT CATEGORIES,SUBCAT ,PRODUCTS THE MAJOR DIVISIONS WITHOUT NULL IN CATEGORIES

SELECT DISTINCT Category,Product FROM Sales.Products
WHERE Category IS NOT NULL
ORDER BY 1,2
