----------------------------------------DIMENSION EXPLORATION-----------------------------------------------------------

--INDENTIFY THE  UNQUE VALUES IN EACH DIMESION  RECOGNIZING HOW DATA GROUPED OR SEGMENTED----

---SYNTAX = DISTINCT[DIMENSION]
--EXAMPLE: DISTINCT[COUNTRY],DISTINCT[CATEGORY],DISTINCT[PRODUCT]--

------EXPLORE ALL DISTINCT COUNTRIES OF OUR CUSTOMERS COME FROM-----------
SELECT DISTINCT COUNTRY from gold.dim_Customers

-----EXPLORE ALL CAT,SUCAT,PRODUCTS IN PRODUCTS TABLES
SELECT DISTINCT CATEGORY,SUBCATEGORY,product_name FROM gold.dim_Products
order by 1,2,3
