-------------------------------MAGNITUDE------------------------

----COMPARE THE MESURE VALUES TO DIM(CAT) IT HELPS TO UNDERSTAND IMP OF  DIFF DIM(CAT)------------

--SYNTAX = AGG[MEASURE] BY [DIM]
--EXAMPLE:  TOTAL SALES BY COUNTRY,TOATL QUANTITY BY CAT, AVG PRICE BY PRODUCT,TOTAL ORDERS BY CUSTOMER

----------FIND TOTAL CUSTOMERS BY COUNTRY----------------------
SELECT Country,COUNT(CUSTOMER_KEY) AS CUSTOMERS_BY_COUNTRY FROM gold.dim_Customers GROUP BY Country
ORDER BY CUSTOMERS_BY_COUNTRY DESC

-----------FIND THE TOTAL CUSTOMESR BY GENDER---------------------
SELECT Gender,COUNT(CUSTOMER_KEY) AS TOTAL_CUSTOMERS FROM gold.dim_Customers GROUP BY Gender
ORDER BY TOTAL_CUSTOMERS

------FIND THE TOTAL REVENUE GENERATED FOR EACH CUSTOMER-----------------
--HERE TOTAL REVENUE FROM FACT_SALES TABLE AND CATEGORY FROM DIM_CUSTOMERS TABLE SO JOIN TABLES
SELECT
C.Customer_Key,
C.First_Name,
SUM(S.Sales_amount) AS TOTAL_REVENUE
FROM gold.fact_sales as S
LEFT JOIN gold.dim_Customers as C
on S.Customer_Key=C.Customer_Key
group by C.Customer_Key,C.First_Name
ORDER BY TOTAL_REVENUE desc

--------WHAT IS THE DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES----------------
SELECT
C.COUNTRY,
SUM(S.Quantity) AS TOTAL_SOLD_ITEMS
FROM gold.fact_sales as S
LEFT JOIN gold.dim_Customers as C
on S.Customer_Key=C.Customer_Key
group by C.COUNTRY
ORDER BY TOTAL_SOLD_ITEMS desc
