-------------------------------MAGNITUDE------------------------

----COMPARE THE MESURE VALUES TO DIM(CAT) IT HELPS TO UNDERSTAND IMP OF  DIFF DIM(CAT)------------

--SYNTAX = AGG[MEASURE] BY [DIM]
--EXAMPLE:  TOTAL SALES BY COUNTRY,TOATL QUANTITY BY CAT, AVG PRICE BY PRODUCT,TOTAL ORDERS BY CUSTOMER

---------FIND THE TOTAL EMPLOYEES BY GENDER-

SELECT
GENDER, 
CASE WHEN Gender= 'F' THEN 'FEMALE'
     WHEN Gender= 'M' THEN 'MALE'
END GENDER_Category,
COUNT(DISTINCT EmployeeID) AS TOTAL_EMPLOYEES
FROM Sales.Employees
GROUP BY Gender

--------FIND THE TOTAL REVENUE GENERTED FOR  EACH CATEGORY-----------

-----HERE REVENUE(SALES) COMES FROM (SALES.ORDERS)TABLE, CATEGORY CAME FROM (SALES.PRODUCTS) TABLE SO WE USE LEFT JOIN TO JOIN THE TABLES

SELECT
P.Category,
SUM(O.Sales) AS TOTAL_SALES
FROM Sales.Orders AS O
LEFT JOIN SALES.Products AS P
ON O.ProductID=P.ProductID
GROUP BY Category
ORDER BY TOTAL_SALES

