---------------------------------------------------MEASURE EXPLORATION------------------------------------------------------------

--CALCULATE HIGHEST AND LOWEST LEVEL OF AGGREGATION USING SUM,AVG,COUNT E.T.C---------------------

--SYNTAX = AGG[MEASURE]--
--EXAMPLE: SUM(SALES),AVG(PRICE),SUM(QUANTITY),COUNT(SALES)---

--FIND TOTAL SALES
SELECT SUM(Sales) as Total_sales FROM Sales.Orders

--FIND HOW MANY ITEMS SOLD
SELECT SUM(Quantity) AS  TOTAL_QUANTITY FROM Sales.Orders

--FIND TOTAL NO. OF ORDERS WITHOUT NULLS
SELECT COUNT(ORDERID) AS TOTAL_ORDERS FROM Sales.Orders WHERE OrderID IS NOT NULL
-------WE CAN ALSO USE DISNTINCT-----------
SELECT COUNT(DISTINCT ORDERID) AS TOTAL_ORDERS FROM Sales.Orders
