------------------------------PART TO WHOLE ANALYSIS----------------------------------

-------------ANALYZE HOW INDIVIDUAL PART PERFORMING COMPARED TO OVERALL------------

-----SYNTAX = MEASURE\TOTAL MEASURE *100 BY DIM
-----EXAMPLE:SALES\TOTAL SALES &100 BY CATEGORY

===========================WHICH CATEGORY CONTRIBUTE THE MOST  TO OVERALL SALES==============================================
SELECT
CATEGORY,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER(ORDER BY TOTAL_SALES DESC) AS OVERLL_SALES,
CONCAT(ROUND(CAST(TOTAL_SALES AS FLOAT)/SUM(TOTAL_SALES) OVER()*100,2),'%')AS PERCNT_TOTAL
FROM(
SELECT
P.Category AS CATEGORY,
 SUM(O.Sales) TOTAL_SALES
FROM Sales.Orders AS O
LEFT JOIN Sales.Products AS P
ON O.ProductID=P.ProductID
GROUP BY Category)t
