------------------------------PART TO WHOLE ANALYSIS----------------------------------

-------------ANALYZE HOW INDIVIDUAL PART PERFORMING COMPARED TO OVERALL------------

-----SYNTAX = MEASURE\TOTAL MEASURE *100 BY DIM
-----EXAMPLE:SALES\TOTAL SALES &100 BY CATEGORY

--------ANALYZE WHICH COUNTRY CONTRIBURTES THE MOST TO OVER ALL PRICE-----------
------HERE WE NEED TO JOIN  TABLES------------
SELECT
COUNTRY,
TOTAL_PRICE,
SUM(TOTAL_PRICE) OVER() AS OVERALL_TOTAL,
CONCAT(ROUND(CAST(TOTAL_PRICE AS float)/SUM(TOTAL_PRICE) OVER() * 100,2),'%') AS PERCENTAGE_TOTAL
FROM(

SELECT
C.Country AS COUNTRY,
SUM(S.Price) AS TOTAL_PRICE
FROM gold.fact_sales AS S
LEFT JOIN gold.dim_Customers AS C
ON S.Customer_Key=C.Customer_Key
GROUP BY C.Country
)t
