---------------------------------------------PERFORMANCE ANALYSIS----------------------------------------------

---COMPRING CURR VALUE TO TARGET VALUE, HELPS TO MEASURE SUCESS AND COMPARE PERFORMANCE------

---SYNTAX = CURR MESURE - TARGET MEASURE
---EXAMPLE: CURR SALES- AVG SALES----------------

 ---ANALYZE THE YEARLY PERFORMANCE OF sales BY COMPARING THEIR SALES TO BOTH AVG SALES
---AND PREV YEAR SALES------------
 SELECT
 ORDER_YEAR,
 CURR_SALES,
 AVG(CURR_SALES)OVER(PARTITION BY ORDER_YEAR ) AS AVG_SALES,
 CURR_SALES-AVG(CURR_SALES)OVER(PARTITION BY ORDER_YEAR ORDER BY CURR_SALES) AS DIFF_AVG,
 LAG(CURR_SALES) OVER (PARTITION BY ORDER_YEAR ORDER BY CURR_SALES) AS PREV_SALES,
 CURR_SALES-LAG(CURR_SALES) OVER (PARTITION BY ORDER_YEAR ORDER BY CURR_SALES) AS DIFF_YEARS
 FROM(
 SELECT
 YEAR(Order_Date) AS ORDER_YEAR,
 SUM(Sales_amount) AS CURR_SALES
 FROM gold.fact_sales
 where Order_Date is not null
 GROUP BY YEAR(Order_Date)
 )t
