---------------------------------------------PERFORMANCE ANALYSIS----------------------------------------------

---COMPRING CURR VALUE TO TARGET VALUE, HELPS TO MEASURE SUCESS AND COMPARE PERFORMANCE------

---SYNTAX = CURR MESURE - TARGET MEASURE
---EXAMPLE: CURR SALES- AVG SALES----------------

=============ANALYZE THE  MONTHLY PERFORMANCE OF PRODUCTS BY COMPARING EACH  PRODUCT SALES TO BOTH AVG SALES AND PREV YEAR SALES==========
SELECT
ORDER_MONTH,
PRODUCT,
CURRTOTAL_SALES,
avg(CURRTOTAL_SALES)over(partition by product) AS AVG_SALES,
CURRTOTAL_SALES-avg(CURRTOTAL_SALES)over(partition by product) AS DIFF_AVG,
CASE WHEN CURRTOTAL_SALES-avg(CURRTOTAL_SALES)over(partition by product)>0 THEN 'ABOVE AVG'
     WHEN CURRTOTAL_SALES-avg(CURRTOTAL_SALES)over(partition by product)<0 THEN 'BELOW AVG'
	 ELSE 'AVG'
END  AVG_CHANGE,
==============MONTH OVER MONTH ANALYSIs==================
LAG(CURRTOTAL_SALES) OVER(ORDER BY ORDER_MONTH) PREVIOS_SALES,
CURRTOTAL_SALES-LAG(CURRTOTAL_SALES) OVER(ORDER BY ORDER_MONTH) AS DIFF_PYMONTH,
CASE WHEN CURRTOTAL_SALES-avg(CURRTOTAL_SALES)over(ORDER BY ORDER_MONTH)>0 THEN 'INCREASE'
     WHEN CURRTOTAL_SALES-avg(CURRTOTAL_SALES)over(ORDER BY ORDER_MONTH)<0 THEN 'DECRESE'
	 ELSE 'NO CHANGE'
END PY_CHANGE
from(

SELECT
MONTH(O.OrderDate)AS ORDER_MONTH,
SUM(O.Sales) AS CURRTOTAL_SALES,
P.Product AS PRODUCT
FROM Sales.Orders AS O
LEFT JOIN Sales.Products AS P
ON O.ProductID=P.ProductID
GROUP BY MONTH(O.OrderDate),P.Product)t
