-----------------------------------------RANKING(TOP-N/BOTTOM-N)-----------------------------------------------

------ORDER THE VALUES OF DIM BY MEASURE FOR IDENTIFYING TOP-N & BOTTOM-N PERFORMERS--

---SYNTAX = RANK[DIM] B MEASURE
---EXAMPLE: RANK COUNTRY BY TOTAL SALES , TOP5 PRODUCTS BY QUANTITY ,E.T.C

--------------------FIND TOP 10 CUSTOMERS GENERATED BY TOTAL SALES--------------
SELECT top 5
C.FIRST_NAME,
SUM(S.Sales_amount) AS TOTAL_SALES
FROM gold.fact_sales  AS S
LEFT JOIN gold.dim_Customers AS C
ON S.Customer_Key=C.Customer_Key
GROUP BY C.FIRST_NAME 
order by TOTAL_SALES desc

----solve the same task using windo functions------------
SELECT
*
FROM(
SELECT 
C.FIRST_NAME,
SUM(S.Sales_amount) AS TOTAL_SALES,
rank() over(order by SUM(S.Sales_amount) desc) as RANK
FROM gold.fact_sales  AS S
LEFT JOIN gold.dim_Customers AS C
ON S.Customer_Key=C.Customer_Key
GROUP BY C.FIRST_NAME )t where RANK<=5

--------FIND 3 CUSTOMESR WITH LESS ORDERS PLACED-----------------
SELECT TOP 3
C.FIRST_NAME,
COUNT(DISTINCT Order_Number) AS TOTAL_ORDERS
FROM gold.fact_sales AS S 
LEFT JOIN gold.dim_Customers AS C
ON S.Customer_Key=C.Customer_Key
GROUP BY C.FIRST_NAME
ORDER BY TOTAL_ORDERS ASC

----solve the same task using windo functions------------
SELECT
*
FROM(
SELECT TOP 3
C.FIRST_NAME,
COUNT(DISTINCT Order_Number) AS TOTAL_ORDERS,
RANK() OVER(ORDER BY COUNT(DISTINCT Order_Number) ASC) AS RANK_OF_ORDER
FROM gold.fact_sales AS S 
LEFT JOIN gold.dim_Customers AS C
ON S.Customer_Key=C.Customer_Key
GROUP BY C.FIRST_NAME)t where RANK_OF_ORDER<=3

